# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('pp', models.CharField(max_length=8)),
                ('keywords', models.TextField()),
                ('abstract', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_name', models.CharField(max_length=30)),
                ('conf_val', models.CharField(max_length=30)),
                ('pic_url', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.IntegerField()),
                ('month', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=5)),
                ('pp', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Volumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_year', models.CharField(max_length=5)),
                ('high_year', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='volumes',
            name='yearrange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal.YearRange'),
        ),
        migrations.AddField(
            model_name='issues',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal.Volumes'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal.Issues'),
        ),
    ]
