# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pp',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='conf_val',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='pic_url',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='pp',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
