# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0004_auto_20190620_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.CharField(choices=[('index', 'index'), ('revs', 'reviews'), ('RA', 'research articles')], default='RA', max_length=6),
        ),
    ]
