# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0005_article_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
