# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0006_auto_20190623_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='refrences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
